version: '2'

services:
  site:
    command: jekyll serve
    image: jekyll/builder:latest
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
